name: Approve self-created pull requests

on:
  issue_comment:
    types: [created]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        name: Approve self-created pull requests
        with:
          script: console.log("check")

      - uses: actions/github-script@v6
        name: Approve self-created pull requests
        # if a user that created the PR is the same user that left a comment
        # and that comment starts with /approve, then autoapprove it
        if: >-
          github.event.issue.user.login == github.actor &&
          startsWith(github.event.comment.body, "/approve") &&
          github.actor == "shishifubing"
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: "APPROVE",
              body: "Self-approved by ${github.actor}"
            })
