name: "terraform"

on:
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.TERRAFORM_TOKEN_GITHUB }}
  GITLAB_TOKEN: ${{ secrets.TERRAFORM_TOKEN_GITLAB }}
  AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_BUCKET_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_BUCKET_KEY }}

jobs:
  call:
    uses: shishifubing-com/ci-actions-common/.github/workflows/terraform.yml@test/without-secrets
