name: "terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    uses: shishifubing-com/ci-actions-common/.github/workflows/terraform.yml@feature/add-terraform-workflow
    secrets: inherit
