name: "terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call:
    uses: shishifubing-com/ci-actions-common/.github/workflows/terraform.yml@test/mask-env
    with:
      env: |
        AWS_ACCESS_KEY_ID=${{ secrets.TERRAFORM_BUCKET_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.TERRAFORM_BUCKET_KEY }}
        GITLAB_TOKEN=${{ secrets.TERRAFORM_TOKEN_GITLAB }}
        GITHUB_TOKEN=${{ secrets.TERRAFORM_TOKEN_GITHUB }}
      mask: |
        ${{ secrets.TERRAFORM_BUCKET_ID }}
        ${{ secrets.TERRAFORM_BUCKET_KEY }}
        ${{ secrets.TERRAFORM_TOKEN_GITLAB }}
        ${{ secrets.TERRAFORM_TOKEN_GITHUB }}
