name: terraform

on:
  schedule:
    # runs at 00:00
    - cron: 0 0 * * *
  push:
    paths: 
      - "**/*.tf"
      - .github/**
    branches:
      - main
  pull_request:
    paths: 
      - "**/*.tf"
      - .github/**/*

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.3.7
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_BUCKET_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_BUCKET_KEY }}
      GITLAB_TOKEN: ${{ secrets.TERRAFORM_TOKEN_GITLAB }}
      GITHUB_TOKEN: ${{ secrets.TERRAFORM_TOKEN_GITHUB }}

    steps:
      - name: Run terraform
        uses: shishifubing/ci-actions-common/actions/terraform@main
      
      - name: Rerun terraform
        if: failure()
        uses: shishifubing/ci-actions-common/actions/terraform@main
